--tim tien max
SELECT *
FROM
	(SELECT B.BRANCH_ID,
			SUM(QUANTITY * PRICE + DISTANCE * 5000) AS REV
		FROM CM_BRANCH B
		JOIN CM_STAFF ST ON ST.BRANCH_ID = B.BRANCH_ID
		JOIN CM_ORDER OD ON OD.STAFF_ID = ST.STAFF_ID
		JOIN CM_ORDERED_ITEM OI ON OI.ORDER_ID = OD.ORDER_ID
		GROUP BY B.BRANCH_ID) REV
WHERE REV =
		(SELECT MAX(REV)
			FROM
				(SELECT SUM(QUANTITY * PRICE + DISTANCE * 5000) AS REV
					FROM CM_BRANCH B
					JOIN CM_STAFF ST ON ST.BRANCH_ID = B.BRANCH_ID
					JOIN CM_ORDER OD ON OD.STAFF_ID = ST.STAFF_ID
					JOIN CM_ORDERED_ITEM OI ON OI.ORDER_ID = OD.ORDER_ID
					GROUP BY B.BRANCH_ID) AS T)



	(SELECT 
			SUM(QUANTITY * PRICE + DISTANCE * 5000) AS REV
		FROM CM_BRANCH B
		JOIN CM_STAFF ST ON ST.BRANCH_ID = B.BRANCH_ID
		JOIN CM_ORDER OD ON OD.STAFF_ID = ST.STAFF_ID
		JOIN CM_ORDERED_ITEM OI ON OI.ORDER_ID = OD.ORDER_ID
		GROUP BY B.BRANCH_ID) REV
WHERE REV =
		(SELECT MAX(REV)
			FROM
				(SELECT SUM(QUANTITY * PRICE + DISTANCE * 5000) AS REV
					FROM CM_BRANCH B
					JOIN CM_STAFF ST ON ST.BRANCH_ID = B.BRANCH_ID
					JOIN CM_ORDER OD ON OD.STAFF_ID = ST.STAFF_ID
					JOIN CM_ORDERED_ITEM OI ON OI.ORDER_ID = OD.ORDER_ID
					GROUP BY B.BRANCH_ID) )